export { runEngine, type EngineDeps, type EngineResult } from "./engine.ts";
export { DEFAULT_CONFIG, ENGINE_VERSION, GENERATOR_NAMES, configHash, resolveConfig, type EngineConfig, type EngineConfigInput, type GeneratorName } from "./config.ts";
export * from "./types.ts";
export { localEmbed, cosine, tokenize, type EmbedFn } from "./embed.ts";
export { JudgeCache, judgeCacheKey, parseVerdict, buildJudgeMessages, judgeOne } from "./judge.ts";
export { candidateReason, memberReason, pairReason, type FilterReason } from "./filters.ts";
export { composeGroup } from "./group.ts";
export { gini, lorenz } from "./policy.ts";
export { harmonic, mutualBenefit, netValue } from "./scoring.ts";
export { World, buildWorld } from "./world.ts";
export * as opportunity from "./opportunity.ts";
export * as outreach from "./outreach.ts";
export { MatcherScheduler, MemoryProposalStore, type ProposalStore } from "./tick.ts";
export { Rng } from "./rng.ts";
export * as attention from "./attention.ts";
export { DEFAULT_ATTENTION, resolveAttention, attentionConfigHash, type AttentionConfig, type AttentionConfigInput } from "./config.ts";
export * as plans from "./plans.ts";
export { DEFAULT_PLANS, resolvePlans, plansConfigHash, type PlansConfig, type PlansConfigInput } from "./config.ts";
// App packs (docs/results/2026-10-08-app-packs-core.md): the contract, the core geo model and networkPack.
export * from "./pack.ts";
export { cityBucketGeo } from "./geo.ts";
export { networkPack, NETWORK_PACK_VERSION } from "./packs/network/index.ts";
