#!/usr/bin/env bun
// Builds the SKILL.md snapshots in the two plugins from the one source, sites/skills/<name>/SKILL.md.
// Never edit a snapshot by hand: change the source, then run this. ChatGPT and Codex import the
// skills when the plugin is submitted and do not fetch them again, so a change needs a new plugin version.
//   bun run plugins/build.ts           write plugins/openai/skills and plugins/claude/skills
//   bun run plugins/build.ts --check   exit 1 if a snapshot differs from a fresh build (tests run this)
//
// The OpenAI plugin leaves out slop.date: OpenAI requires plugins that suit people aged 13-17
// (developers.openai.com/plugins/plugin-guidelines). Its copy of the hub skill is cut down to the
// other apps, and the build fails if "slop" or "dating" is left anywhere in plugins/openai.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { DEFAULT_BACKEND_ORIGIN } from "../sites/skills.config.ts";

const ROOT = import.meta.dir;
const SOURCE = join(ROOT, "..", "sites", "skills");

export const SITE: Record<string, string> = { "ntwrk-love": "ntwrk.love", "slop-date": "slop.date", "peon-biz": "peon.biz", "friends-help": "friends.help" };
/** The one MCP endpoint of the OpenAI plugin (OpenAI allows one server per plugin). It never lists slop. */
export const OPENAI_MCP_URL = "https://ntwrk.love/mcp/openai";
/** Each site is its own MCP resource: a connection covers that one app. */
export const siteMcpUrl = (skill: string) => `https://${SITE[skill]}/mcp`;

export const PLUGINS = {
  openai: { skills: ["ntwrk-love", "peon-biz", "friends-help"], mcpUrl: (_: string) => OPENAI_MCP_URL },
  claude: { skills: ["ntwrk-love", "slop-date", "peon-biz", "friends-help"], mcpUrl: siteMcpUrl },
} as const;

const fill = (text: string, mcpUrl: string) =>
  text.replaceAll("{{BACKEND_ORIGIN}}", DEFAULT_BACKEND_ORIGIN).replaceAll("{{MCP_URL}}", mcpUrl);

/** Remove slop.date from a skill for the OpenAI plugin: inline mentions, then whole table rows and list items. */
export function withoutSlop(md: string): string {
  const inline = md
    .replace(/slop\.date \(dating\), /g, "")
    .replace(/ntwrk\.love, slop\.date, /g, "ntwrk.love, ")
    .replace(/"leave slop\.date"/g, '"leave peon.biz"')
    .replace(/ Dating details never move\./g, "");
  const out: string[] = [];
  const lines = inline.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (line.startsWith("|") && /slop/i.test(line)) continue;
    if (/^- /.test(line)) {
      // A list item and its indented continuation lines.
      let j = i + 1;
      while (j < lines.length && /^ {2}\S/.test(lines[j]!)) j++;
      const item = lines.slice(i, j);
      if (item.some(l => /slop/i.test(l))) { i = j - 1; continue; }
    }
    out.push(line);
  }
  return out.join("\n");
}

/** The MCP dependency of an OpenAI skill (developers.openai.com/plugins/build/skills). */
const openaiYaml = () => `# Generated by plugins/build.ts. Do not edit.
dependencies:
  tools:
    - type: mcp
      value: the-network
      description: The Network's MCP server. app_info and start_signup need no sign-in. check_status needs the person to sign in on ntwrk.love themselves.
      transport: streamable_http
      url: ${OPENAI_MCP_URL}
`;

export function build(): Map<string, string> {
  const files = new Map<string, string>();
  for (const [plugin, p] of Object.entries(PLUGINS)) {
    for (const skill of p.skills) {
      const src = readFileSync(join(SOURCE, skill, "SKILL.md"), "utf8");
      let text = fill(src, p.mcpUrl(skill));
      if (plugin === "openai") text = withoutSlop(text);
      if (text.includes("{{")) throw new Error(`${plugin}/${skill}: an unfilled {{placeholder}} is left`);
      if (plugin === "openai" && /slop|dating/i.test(text)) throw new Error(`openai/${skill}: slop.date is still mentioned; extend withoutSlop()`);
      files.set(join(plugin, "skills", skill, "SKILL.md"), text);
      if (plugin === "openai") files.set(join(plugin, "skills", skill, "agents", "openai.yaml"), openaiYaml());
    }
  }
  return files;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const files = build();
  const stale: string[] = [];
  for (const [rel, text] of files) {
    const path = join(ROOT, rel);
    const cur = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (cur === text) continue;
    if (check) stale.push(rel);
    else { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, text); console.log(`wrote plugins/${rel}`); }
  }
  for (const plugin of Object.keys(PLUGINS)) {
    const dir = join(ROOT, plugin, "skills");
    const want = new Set(PLUGINS[plugin as keyof typeof PLUGINS].skills as readonly string[]);
    for (const d of existsSync(dir) ? readdirSync(dir) : []) if (!want.has(d)) stale.push(`${plugin}/skills/${d} (not in the plugin; delete it)`);
  }
  if (stale.length) { console.error(`stale snapshots (run bun run plugins/build.ts):\n  ${stale.join("\n  ")}`); process.exit(1); }
  if (check) console.log("plugin skill snapshots are up to date");
}
